services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mqtt
    environment:
      MQTT_WSS_HOSTNAME: ${MQTT_WSS_HOSTNAME}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    network_mode: host
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  cognex-ftp:
    image: fauria/vsftpd
    container_name: cognex-ftp
    restart: unless-stopped
    network_mode: host
    environment:
      FTP_USER: cognex
      FTP_PASS: cognex
      PASV_ADDRESS: 192.168.103.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      LOCAL_UMASK: 022
      FILE_OPEN_MODE: 0666
    volumes:
      - ${COGNEX_FTP_UPLOAD_DIR}:/home/vsftpd/cognex

volumes:
  caddy_data:
  caddy_config:
  mongo_data:
